### ISSUE TITLE
Seems to have a lot of options

### ISSUE THREAD

**Issue by ctycode** [stablecog/sc-worker#1]
I am deploying STABLECOG locally and looking at the repository on github it seems that there are two repos for the image generation service. [sc-cog](https://github.com/stablecog/stable-diffusion-cog) and this repo, one should I choose?

**Comment by ctycode** [comment]
Can the current repo be deployed to replicate?

**Comment by yekta** [comment]
Sc-worker is the one we are using currently, sc-cog is outdated. Current repo can't be deployed to Replicate, it connects to Redis and other services.

**Comment by ctycode** [comment]
Thank you for your reply. I saw that the blog mentioned that the service is running on A100. The current running mode of repo is not the serverless mode. It is conceivable that the running cost of A100 is quite expensive. How much do you currently pay for gpu? I have some idle A100 resources here, which can be provided to you for free.

**Comment by yekta** [comment]
GitHub issues isn't a good place to discuss these things. Issues are for directly code related things. You can come to our Discord and we can continue from there.
